title: "سمسار طلبك"
email: "elraikonly@outlook.sa"
description: "بوابتك العقارية الأولى في مدينة نصر."
url: "https://aqarnasr.netlify.app"
baseurl: ""
lang: "ar"
timezone: Africa/Cairo

author:
  name: "طارق طنطاوي"
logo: "/assets/img/logo.png"

# العودة للنظام العادي (بدون pretty) لتعمل روابط .html
markdown: kramdown

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - build.sh
  - README.md

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      image: "/assets/img/logo.png"
