# =========================================================
# ===    إعدادات المصنع العقاري (النسخة الذهبية)       ===
# =========================================================

title: "سمسار طلبك"
email: "elraikonly@outlook.sa"
description: "بوابتك العقارية الأولى في مدينة نصر."
url: "https://aqarnasr.netlify.app"
baseurl: ""
lang: "ar"
timezone: Africa/Cairo

# بيانات المالك (للسيو)
author:
  name: "طارق طنطاوي"
logo: "/assets/img/logo.png"

# إعدادات البناء
markdown: kramdown

# الإضافات (تم حذف jekyll-sitemap لأننا سنبني الخريطة يدوياً)
plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - build.sh
  - README.md
  - generate_sitemap.py # استبعاد سكربت البناء من الموقع النهائي

# صورة افتراضية للمشاركة
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      image: "/assets/img/logo.png"
